# Generated by Django 3.0.4 on 2020-06-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askManage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='reason',
        ),
        migrations.AddField(
            model_name='ask',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
