# Generated by Django 3.0.4 on 2020-03-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='headshot',
            field=models.ImageField(blank=True, upload_to='headshot'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_infor',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
