# Generated by Django 3.0.4 on 2020-06-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0004_auto_20200604_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
