# Generated by Django 3.0.4 on 2020-06-13 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0005_userprofile_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birthday',
        ),
    ]
