# Generated by Django 3.0.4 on 2020-06-08 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0006_articlecomment_canbeseen'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCommentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('Administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VideocommentAdministrator', to=settings.AUTH_USER_MODEL)),
                ('bookcomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VideocommentReport', to='comment.VideoComment')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VideocommentReport', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookCommentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('Administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BookcommentAdministrator', to=settings.AUTH_USER_MODEL)),
                ('bookcomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BookcommentReport', to='comment.BookComment')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BookcommentReport', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCommentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('Administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ArticlecommentAdministrator', to=settings.AUTH_USER_MODEL)),
                ('bookcomment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ArticlecommentReport', to='comment.ArticleComment')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ArticlecommentReport', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
