# Generated by Django 3.0.4 on 2020-06-08 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecommentreport',
            old_name='bookcomment',
            new_name='articlecomment',
        ),
        migrations.RenameField(
            model_name='videocommentreport',
            old_name='bookcomment',
            new_name='videocomment',
        ),
    ]
