# Generated by Django 3.0.4 on 2020-03-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Book_img',
            field=models.ImageField(default=0, upload_to='img'),
            preserve_default=False,
        ),
    ]
