# Generated by Django 3.0.4 on 2020-04-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_auto_20200327_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Book_total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
