# Generated by Django 3.0.4 on 2020-04-08 03:37

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('Books', '0006_auto_20200407_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Book_tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
