# Generated by Django 3.0.4 on 2020-06-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topicimg',
            field=models.ImageField(null=True, upload_to='topicimg/'),
        ),
    ]
