# Generated by Django 3.0.4 on 2020-05-26 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usergroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=100)),
                ('createdTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('groupsize', models.IntegerField(default=0)),
                ('group_img', models.ImageField(null=True, upload_to='groupimg')),
                ('group_info', models.TextField(blank=True, max_length=1000)),
                ('groupMaster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
