# Generated by Django 3.0.4 on 2020-05-26 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usergroup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='users',
            new_name='members',
        ),
    ]
