# Generated by Django 3.0.4 on 2020-05-26 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Usergroup', '0002_auto_20200526_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='groupMaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupmaster', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='groupsize',
            field=models.IntegerField(default=1),
        ),
    ]
