# Generated by Django 3.0.4 on 2020-06-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_videocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='canbeseen',
            field=models.BooleanField(default=True),
        ),
    ]
