# Generated by Django 3.0.4 on 2020-06-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_auto_20200610_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='hates',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='hates',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
